apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: devopsschoolacr.azurecr.io/task3_java_postgresql-java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: QA_COURSE_01_RDS_DB_HOST
              value: "postgres-service"
            - name: QA_COURSE_01_RDS_DB_NAME
              value: "mydatabase"
            - name: QA_COURSE_01_RDS_USERNAME
              value: "myuser"
            - name: QA_COURSE_01_RDS_PASSWORD
              value: "password123"